version: "3.7"
services:
  ros2:
    build: .
    network_mode: host
    # restart: no
#    ports: 
#      - "3332:3332"
#      - "11811:11811" # node discoverer
#      - "32650:32650"
#      - "32651:32651"
#      - "32662:32662"
#      - "32663:32663"
    volumes:
      - /home/yuxuan/ros:/home/ros
      - /home/yuxuan/Documents/my_ros2:/ros2
    devices:
     - /dev/video0:/dev/video0
     - /dev/ttyAMA0:/dev/ttyAMA0
    tty: true
    environment:
      - DISPLAY
